# See all available configuration options at:
# https://embarkstudios.github.io/cargo-deny/index.html

# --------------------------------------------------
# General
# --------------------------------------------------

all-features = true
no-default-features = true

# --------------------------------------------------
# BANS
# --------------------------------------------------

[bans]
highlight = "all"
wildcards = "deny"
multiple-versions = "allow"
workspace-default-features = "allow"
external-default-features = "allow"

# --------------------------------------------------
# SOURCES
# --------------------------------------------------

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

# --------------------------------------------------
# ADVISORIES
# --------------------------------------------------

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
db-path = "~/.cargo/advisory-db"
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
severity-threshold = "None"
ignore = []

# --------------------------------------------------
# LICENSES
# --------------------------------------------------

[licenses]
default = "deny"
copyleft = "warn"
unlicensed = "deny"
allow = [
	"MIT",
	"Zlib",
	"BSL-1.0",
	"Apache-2.0",
	"BSD-3-Clause",
	"Unlicense",
]
confidence-threshold = 0.95

[[licenses.exceptions]]
name = "unicode-ident"
version = "*"
allow = ["Unicode-DFS-2016"]